#!/usr/bin/env python3
"""
Extracts tiles from an mbtiles file generated by Tippecanoe.
Tippecanoe uses a different schema than Planetiler, so we need this separate script.
"""
import json
import sqlite3
import sys
from pathlib import Path

import click


@click.command()
@click.argument(
    'mbtiles_path',
    type=click.Path(exists=True, dir_okay=False, file_okay=True, path_type=Path),
)
@click.argument('dir_path', type=click.Path(dir_okay=True, file_okay=False, path_type=Path))
def cli(mbtiles_path: Path, dir_path: Path):
    """
    Extracts a Tippecanoe mbtiles sqlite to a folder.
    
    Tippecanoe uses a view 'tiles' that joins 'map' and 'images' tables.
    """

    if dir_path.exists() and any(dir_path.iterdir()):
        sys.exit('  dir not empty')

    dir_path.mkdir(exist_ok=True)
    tiles_dir = dir_path / 'tiles'
    tiles_dir.mkdir(exist_ok=True)

    conn = sqlite3.connect(mbtiles_path)
    c = conn.cursor()

    # Get total tile count
    total = c.execute('select count(*) from tiles').fetchone()[0]
    print(f'Extracting {total} tiles...')

    # Extract tiles from the tiles view
    c.execute('select zoom_level, tile_column, tile_row, tile_data from tiles')
    for i, row in enumerate(c, start=1):
        z = row[0]
        x = row[1]
        # TMS to XYZ conversion (flip Y)
        y = (1 << z) - 1 - row[2]
        tile_data = row[3]

        tile_path = tiles_dir / str(z) / str(x) / f'{y}.pbf'
        tile_path.parent.mkdir(parents=True, exist_ok=True)
        with open(tile_path, 'wb') as fp:
            fp.write(tile_data)

        if i % 100 == 0 or i == total:
            print(f'  Extracted {i}/{total} tiles')

    # Write metadata
    write_metadata(c, dir_path=dir_path)
    conn.close()

    print(f'extract_tippecanoe_mbtiles.py DONE - tiles in {tiles_dir}')


def write_metadata(c, *, dir_path):
    """Write metadata.json from mbtiles metadata table."""
    metadata = dict(c.execute('select name, value from metadata').fetchall())
    
    # Ensure osm_date is present (for contour tiles, we use contour generation date)
    if 'osm_date' not in metadata:
        if 'contour_area' in metadata:
            # Use today's date for contour tiles
            from datetime import datetime
            metadata['osm_date'] = datetime.now().strftime('%Y-%m-%d')

    with open(dir_path / 'metadata.json', 'w') as fp:
        json.dump(metadata, fp, indent=2)

    if 'osm_date' in metadata:
        with open(dir_path / 'osm_date', 'w') as fp:
            fp.write(metadata['osm_date'])

    print(f'  Written metadata.json')


if __name__ == '__main__':
    cli()
